spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/icecmspro?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: icecmspro
    password: IceCMS@2024#User
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    username: icecmspro
    password: IceCMS@2024#User
    host: smtp.qq.com
    protocol: smtp
  redis:
    host: localhost
    port: 6379
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
mybatis-plus:
  mapper-locations: classpath:com/ttice/mapper/xml/*.xml
server:
  address: 0.0.0.0
  port: 8181
